import math
import sympy as sp
import sympy.codegen.cfunctions
# [name for name,v in math.__dict__.items() if callable(v)]

MAPPING = {
    math.acos : 'sympy.acos',
    math.acosh : 'sympy.acosh',
    math.asin : 'sympy.asin',
    math.asinh : 'sympy.asinh',
    math.atan : 'sympy.atan',
    math.atan2 : 'sympy.atan2',
    math.atanh : 'sympy.atanh',
    math.ceil : 'sympy.ceiling',
    math.copysign : None,
    math.cos : 'sympy.cos',
    math.cosh : 'sympy.cosh',
    math.degrees : None,
    math.dist : None,
    math.erf : 'sympy.erf',
    math.erfc : 'sympy.erfc',
    math.exp : 'sympy.exp',
    math.expm1 : 'sympy.codegen.cfunctions.expm1',
    math.fabs : 'sympy.Abs',
    math.factorial : 'sympy.factorial',
    math.floor : 'sympy.floor',
    math.fmod : 'sympy.Mod',
    math.frexp : None,
    math.fsum : 'sympy.Sum',
    math.gamma : 'sympy.gamma',
    math.gcd : 'sympy.gcd',
    math.hypot : None,
    math.isclose : None,
    math.isfinite : None,
    math.isinf : None,
    math.isnan : None,
    math.isqrt : None,
    math.lcm : 'sympy.lcm',
    math.ldexp : None,
    math.lgamma : None,
    math.log : 'sympy.log',
    math.log1p : 'sympy.codegen.cfunctions.log1p',
    math.log10 : 'sympy.codegen.cfunctions.log10',
    math.log2 : 'sympy.codegen.cfunctions.log2',
    math.modf : None,
    math.pow : 'sympy.Pow',
    math.radians : None,
    math.remainder : None,
    math.sin : 'sympy.sin',
    math.sinh : 'sympy.sinh',
    math.sqrt : 'sympy.sqrt',
    math.tan : 'sympy.tan',
    math.tanh : 'sympy.tanh',
    math.trunc : 'sympy.trunc',
    math.prod : 'sympy.prod',
    math.perm : None,
    math.comb : None,
    math.nextafter : None,
    math.ulp : None,
}

SUPPORTED = [key.__name__ for key,val in MAPPING.items() if val is not None]